test: &default

  # Credentials for REST APIs
  client_id: AajDkIeamLrQkjCqsm1hP1DvWXJjdSzs5R5YZRHUJ-S8ppUdD-ImPtaZTVZbM8cKkvEtlHB6TA-TyEWJ
  client_secret: EGMUPJw3Fvy1pdbrmNUDRoWB8E4HkvRfZfBZdgiQfJp1Nmi5BvJ9ZVwL8y6u4FTL7wWdPWFhkLbpTmZx

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: stolowka@email.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
